name: Unit Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: setup docker
        uses: docker/setup-buildx-action@v1
      - name: build and test
        run: |
          docker build -t sai2003/frontend:latest .
          docker run sai2003/frontend:latest npm test
